x-service-templates:
  base-app: &base-app
    network_mode: "none"
    image: 7se7en/rinha-de-backend-2026-app-asm:v67
    volumes:
      - sockets:/app/sockets:rw
    logging:
      driver: "none"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 140MB

services:
  app-1:
    <<: *base-app
    environment:
      MODE: "B"
      APP_ID: "APP_1"
      APP_SOCK_PATH: "sockets/one.sock"
  app-2:
    <<: *base-app
    environment:
      MODE: "B"
      APP_ID: "APP_2"
      APP_SOCK_PATH: "sockets/two.sock"

  lb:
    image: 7se7en/rinha-de-backend-2026-app-lb:v67
    ports:
      - "9999:80"
    volumes:
      - sockets:/sockets
    logging:
      driver: "none"
    ulimits:
      nofile:
        soft: 65535
        hard: 200000
    networks:
      - lb-net
    depends_on:
      - app-1
      - app-2
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "30MB"

volumes:
  sockets:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=16m,nr_inodes=1k,noatime,huge=always,mode=0777"

networks:
  lb-net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: "false"
      com.docker.network.bridge.enable_icc: "false"

